
# tap repositories and their packages

tap homebrew/core
brew cairo
brew direnv
brew emojify
brew fontconfig
brew fontforge
brew freetype
brew fribidi
brew fswatch
brew fzf
brew gdbm
brew gdub
brew gettext
brew ghq
brew git
brew glib
brew go
brew gradle
brew graphite2
brew harfbuzz
brew htop
brew hub
brew icu4c
brew jemalloc
brew jpeg
brew jq
brew libevent
brew libffi
brew libidn2
brew libpng
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvterm
brew libyaml
brew lua
brew luajit
brew mas
brew maven
brew msgpack
brew neovim
brew oniguruma
brew openssl
brew pango
brew pcre
brew peco
brew perl
brew pixman
brew python
brew python@2
brew readline
brew reattach-to-user-namespace
brew rsync
brew ruby
brew sqlite
brew swiftlint
brew the_silver_searcher
brew thefuck
brew tig
brew tmux
brew unibilium
brew vim --with-lua
brew wget
brew xz
brew zsh-autosuggestions
brew zsh-completions
brew zsh-syntax-highlighting

tap homebrew/cask-versions
cask java8

tap homebrew/cask
cask alfred
cask appcleaner
cask docker
cask firefox
cask google-chrome
cask iterm2
cask vivaldi

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --with-powerline

tap shyiko/ktlint
brew ktlint

# Other Cask applications
cask android-sdk
cask discord
cask dropbox
cask gimp
cask hyper
cask slack
cask zeplin

# App Store applications
appstore 905155357 Cybozu Desktop (2.1.1)
appstore 682658836 GarageBand (10.3.1)
appstore 668208984 GIPHY CAPTURE (4.1)
appstore 408981434 iMovie (10.1.9)
appstore 409183694 Keynote (8.1)
appstore 539883307 LINE (5.9.3)
appstore 409203825 Numbers (5.1)
appstore 409201541 Pages (7.1)
appstore 568494494 Pocket (1.7.9)
appstore 931571202 QuickShade (1.2.2)
appstore 425955336 Skitch (2.8.2)
appstore 1278508951 Trello (2.10.7)
appstore 557168941 Tweetbot (2.5.8)
appstore 497799835 Xcode (9.4.1)
