#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# ZDOTDIR=~/workspace/project/dotfiles/zsh

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# PATH
export PATH="/usr/local/bin:$PATH"
export PATH="/home/todoroki/lib/sublime:$PATH"

# PATHs for texLive
export MANPATH=/usr/local/texlive/2014/texmf-dist/doc/
export INFOPATH=/usr/local/texlive/2014/texmf-dist/doc/info
export PATH=/usr/local/texlive/2014/bin/x86_64-linux:$PATH

# PATHs for gmp
export CPLUS_INCLUDE_PATH=/home/todoroki/lib/simpath/gmp/
export CPATH=/home/todoroki/lib/simpath/gmp/
export PATH=/usr/local/gmp/lib/:/home/todoroki/lib/simpath/gmp/:$PATH

# PATHs for sgb
export CPLUS_INCLUDE_PATH=/home/todoroki/lib/simpath/sgb/:$CPLUS_INCLUDE_PATH
export CPATH=/home/todoroki/lib/simpath/sgb/:$CPATH

# PATHs for cweb
export PATH=/home/todoroki/lib/simpath/cweb/:$PATH

# PATHs for learnlib
export PYTHONPATH=/home/todoroki/lib/learnlib/:$PYTHONPATH

# PATHs for CUDD
export CPATH=/home/todoroki/lib/pycudd/cudd-2.4.2/include/:$CPATH
export PYTHONPATH=/home/todoroki/lib/pycudd/pycudd/:$PYTHONPATH
export PYTHONPATH=/home/todoroki/lib/pycudd/cudd-2.4.2/lib/:$PYTHONPATH
export LD_LIBRARY_PATH=/home/todoroki/lib/pycudd/cudd-2.4.2/lib/:$LD_LIBRARY_PATH

# PATHs for nysol
export RUBYLIB=/home/todoroki/lib/nysol/nysol-2.0.0/gem/lib/nysol



