# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

case "${OSTYPE}" in
darwin*)
    export LC_ALL='ja_JP.UTF-8'
    # /usr/bin より homebrew を優先する
    if [ "$(uname -m)" = "arm64" ]; then
        export PATH=/opt/homebrew/bin:$PATH
        eval $(/opt/homebrew/bin/brew shellenv)
    else
        export PATH=/usr/local/bin:$PATH
        eval $(/usr/local/bin/brew shellenv)
    fi
    export HOMEBREW_CASK_OPTS="--appdir=/Applications"
    ;;
esac

if type nvim > /dev/null 2>&1; then
    export EDITOR=nvim
else
    export EDITOR=vim
fi

# PATHs for go
case "${OSTYPE}" in
darwin*)
    export GOROOT=/usr/local/go
    export GOPATH=$HOME/workspace/go
    ;;
linux*)
    export GOROOT=$HOME/lib/go
    ;;
esac
export PATH=$GOROOT/bin:$PATH
export PATH=$GOPATH/bin:$PATH

# for direnv
eval "$(direnv hook zsh)"

# PATHs for git-icdiff
export PATH=$HOME/lib/icdiff:$PATH

# PATHs for git-ignore
export PATH=$HOME/lib/git-ignore:$PATH

# PATHs for android studio
export PATH=$PATH:~/Library/Android/sdk/platform-tools
export PATH=$PATH:~/Library/Android/sdk/tools
export ANDROID_HOME=~/Library/Android/sdk

# for zsh-per-directory-history
export PER_DIRECTORY_HISTORY_TOGGLE=^G^R

# for flutter
export PATH=$HOME/lib/flutter/bin:$PATH

# for asdf
export ASDF_DIR=$(brew --prefix asdf)/libexec

# for cargo
if [ -e $HOME/.cargo/env ]; then
    . "$HOME/.cargo/env"
fi

# for local envs
if [ -e $HOME/.zshenv_local ]; then
    source $HOME/.zshenv_local
fi
