source $HOME/.zplug/zplug
source $HOME/.zsh_plugin

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/workspace/project/dotfiles/zsh/zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/workspace/project/dotfiles/zsh/zprezto/init.zsh"
fi

# 自動補完
autoload -U compinit; compinit

# コマンドの途中でもカーソル位置で補完
setopt complete_in_word

# カーソル位置を保持してファイル名一覧を補完
setopt always_last_prompt

# ディレクトリ名を直接入力するとそこに移動する
setopt auto_cd

# cdした先のディレクトリをディレクトリスタックに保存
setopt auto_pushd

# pushdしたとき、すでにスタックにあれば保存しない
setopt pushd_ignore_dups

# 先頭がスペースのときスタックに保存しない
setopt hist_ignore_space

# 色を使う
setopt prompt_subst

# ヒストリを保存するファイル
HISTFILE=$HOME/.zsh_history

# メモリ上のヒストリ数
HISTSIZE=1000000
SAVEHIST=$HISTSIZE

# 直前と同じコマンドをヒストリに追加しない
setopt hist_ignore_dups

# すぐにヒストリファイルに追記
setopt inc_append_history

# zshプロセス間でヒストリを共有
setopt share_history

# 実行したプロセスが30秒以上かかったらその時間を表示する
REPORTTIME=30

# Ctrl+dでログアウトしないようにする
setopt ignoreeof

# Ctrl+sを使えるようにする
stty stop undef

source $HOME/.zsh_alias
source $HOME/.zsh_function
source $HOME/.zsh_keybind

# enhancdを読み込む
if [ -f $ZPLUG_HOME/repos/b4b4r07/enhancd/enhancd.sh ]; then
    source $ZPLUG_HOME/repos/b4b4r07/enhancd/enhancd.sh
fi

# cdrを読み込む
if [ -f $ZPLUG_HOME/repos/willghatch/zsh-cdr/cdr.plugin.zsh ]; then
    source $ZPLUG_HOME/repos/willghatch/zsh-cdr/cdr.plugin.zsh
fi

